### ISSUE TITLE
boot2docker-vm setup fails due to DYLD_LIBRARY_PATH settings

### ISSUE THREAD

**Issue by mmontag** [boot2docker/boot2docker-cli#148] opened 2014-06-10 00:57 UTC
I downloaded the OS X installer. I'm running OS X 10.8.5 and VirtualBox 4.3.12.

My boot2docker-vm is not starting due to DYLD stuff in my environment. Seems to be an old problem for VBoxManage. 
Here's what I see for `boot2docker init -v`:

```
montag:~ $ boot2docker init -v
2014/06/09 17:11:10 executing: VBoxManage showvminfo boot2docker-vm --machinereadable
2014/06/09 17:11:10 Creating VM boot2docker-vm...
2014/06/09 17:11:10 executing: VBoxManage list vms
2014/06/09 17:11:10 executing: VBoxManage createvm --name boot2docker-vm --register
Virtual machine 'boot2docker-vm' is created and registered.
UUID: 4e832fce-2c78-46ac-a551-79de869e0351
Settings file: '/Users/montag/VirtualBox VMs/boot2docker-vm/boot2docker-vm.vbox'
2014/06/09 17:11:10 executing: VBoxManage showvminfo boot2docker-vm --machinereadable
2014/06/09 17:11:10 Apply interim patch to VM boot2docker-vm (https://www.virtualbox.org/ticket/12748)
2014/06/09 17:11:10 executing: VBoxManage setextradata boot2docker-vm VBoxInternal/CPUM/EnableHVP 1
2014/06/09 17:11:10 executing: VBoxManage modifyvm boot2docker-vm --firmware bios --bioslogofadein off --bioslogofadeout off --bioslogodisplaytime 0 --biosbootmenu disabled --ostype Linux26_64 --cpus 8 --memory 1024 --vram 8 --acpi on --ioapic on --rtcuseutc on --cpuhotplug off --pae on --longmode on --synthcpu off --hpet on --hwvirtex on --triplefaultreset off --nestedpaging on --largepages on --vtxvpid on --vtxux off --accelerate3d off --uart1 0x3F8 4 --uartmode1 server /Users/montag/.boot2docker/boot2docker-vm.sock --boot1 dvd
2014/06/09 17:11:11 executing: VBoxManage showvminfo boot2docker-vm --machinereadable
2014/06/09 17:11:11 Setting NIC #1 to use NAT network...
2014/06/09 17:11:11 executing: VBoxManage modifyvm boot2docker-vm --nic1 nat --nictype1 virtio --cableconnected1 on
2014/06/09 17:11:11 executing: VBoxManage controlvm boot2docker-vm natpf1 ssh,tcp,127.0.0.1,2022,,22
2014/06/09 17:11:11 Port forwarding [ssh] tcp://127.0.0.1:2022 --> :22
2014/06/09 17:11:11 executing: VBoxManage controlvm boot2docker-vm natpf1 docker,tcp,127.0.0.1,2375,,2375
2014/06/09 17:11:11 Port forwarding [docker] tcp://127.0.0.1:2375 --> :2375
2014/06/09 17:11:11 executing: VBoxManage list hostonlyifs
2014/06/09 17:11:11 executing: VBoxManage list dhcpservers
2014/06/09 17:11:11 Creating a new host-only network interface...
2014/06/09 17:11:11 executing: VBoxManage hostonlyif create
0%...10%...20%...30%...40%...50%...60%...70%...80%...90%...100%
2014/06/09 17:11:11 executing: VBoxManage hostonlyif ipconfig dyld: DYLD_ environment variables being ignored because main executable (/Applications/VirtualBox.app/Contents/MacOS/VBoxNetAdp --ip 192.168.59.3 --netmask 255.255.255.0
VBoxManage: error: The host network interface with the given name could not be found
VBoxManage: error: Details: code NS_ERROR_INVALID_ARG (0x80070057), component Host, interface IHost, callee nsISupports
VBoxManage: error: Context: "FindHostNetworkInterfaceByName(name.raw(), hif.asOutParam())" at line 218 of file VBoxManageHostonly.cpp
VBoxManage: error: Could not find interface 'dyld: DYLD_ environment variables being ignored because main executable (/Applications/VirtualBox.app/Contents/MacOS/VBoxNetAdp'
2014/06/09 17:11:11 Failed to create host-only network interface: exit status 2
```

I worked around the issue by doing

```
unset DYLD_LIBRARY_PATH
unset LD_LIBRARY_PATH
```
before `boot2docker init`.

Seems others calling VBoxManage have had to work around this issue as well - https://github.com/mitchellh/vagrant/issues/1258.

**Comment by jsolis** [comment] 2015-01-07 02:33
Thanks @runseb :smile: nothing except for closing VBox, unset DYLD_LIBRARY_PATH, restart, boot2docker init worked for me.

**Comment by lc3t35** [comment] 2015-01-28 13:22
+1 OSX 10.8.5 VBox 4.3.20.
````
boot2docker init -v
Boot2Docker-cli version: v1.4.1
Git commit: 43241cb
2015/01/28 14:09:49 executing: VBoxManage showvminfo boot2docker-vm --machinereadable
2015/01/28 14:09:49 executing: VBoxManage showvminfo boot2docker-vm --machinereadable
2015/01/28 14:09:49 executing: VBoxManage list vms
2015/01/28 14:09:49 executing: VBoxManage createvm --name boot2docker-vm --register
Virtual machine 'boot2docker-vm' is created and registered.
UUID: 67f1ebda-197d-466a-8011-96fb725d66cd
Settings file: '/Users/laurent/VirtualBox VMs/boot2docker-vm/boot2docker-vm.vbox'
2015/01/28 14:09:49 executing: VBoxManage showvminfo boot2docker-vm --machinereadable
2015/01/28 14:09:49 executing: VBoxManage setextradata boot2docker-vm VBoxInternal/CPUM/EnableHVP 1
2015/01/28 14:09:49 executing: VBoxManage modifyvm boot2docker-vm --firmware bios --bioslogofadein off --bioslogofadeout off --bioslogodisplaytime 0 --biosbootmenu disabled --natdnshostresolver1 off --natdnsproxy1 off --ostype Linux26_64 --cpus 4 --memory 2048 --vram 8 --acpi on --ioapic on --rtcuseutc on --cpuhotplug off --pae on --longmode on --synthcpu off --hpet on --hwvirtex on --triplefaultreset off --nestedpaging on --largepages on --vtxvpid on --vtxux off --accelerate3d off --uart1 0x3F8 4 --uartmode1 server /Users/laurent/.boot2docker/boot2docker-vm.sock --boot1 dvd
2015/01/28 14:09:49 executing: VBoxManage showvminfo boot2docker-vm --machinereadable
2015/01/28 14:09:49 executing: VBoxManage modifyvm boot2docker-vm --nic1 nat --nictype1 virtio --cableconnected1 on
2015/01/28 14:09:49 executing: VBoxManage controlvm boot2docker-vm natpf1 ssh,tcp,127.0.0.1,2022,,22
2015/01/28 14:09:50 executing: VBoxManage list hostonlyifs
2015/01/28 14:09:50 executing: VBoxManage list dhcpservers
2015/01/28 14:09:50 executing: VBoxManage hostonlyif create
0%...10%...20%...30%...40%...50%...60%...70%...80%...90%...100%
2015/01/28 14:09:50 executing: VBoxManage hostonlyif ipconfig dyld: DYLD_ environment variables being ignored because main executable (/Applications/VirtualBox.app/Contents/MacOS/VBoxNetAdp --ip 192.168.59.3 --netmask 255.255.255.0
VBoxManage: error: The host network interface with the given name could not be found
VBoxManage: error: Details: code NS_ERROR_INVALID_ARG (0x80070057), component Host, interface IHost, callee nsISupports
VBoxManage: error: Context: "FindHostNetworkInterfaceByName(name.raw(), hif.asOutParam())" at line 218 of file VBoxManageHostonly.cpp
VBoxManage: error: Could not find interface 'dyld: DYLD_ environment variables being ignored because main executable (/Applications/VirtualBox.app/Contents/MacOS/VBoxNetAdp'
error in run: Failed to initialize machine "boot2docker-vm": exit status 2
````
I succeed within VBox GUI to desactivate card 1, reactivate and choose local network, save.
Then no more error with boot2docker init -v 
````
boot2docker init -v
Boot2Docker-cli version: v1.4.1
Git commit: 43241cb
2015/01/28 14:12:13 executing: VBoxManage showvminfo boot2docker-vm --machinereadable
2015/01/28 14:12:13 executing: VBoxManage showvminfo boot2docker-vm --machinereadable
2015/01/28 14:12:13 executing: VBoxManage list vms
2015/01/28 14:12:13 executing: VBoxManage createvm --name boot2docker-vm --register
Virtual machine 'boot2docker-vm' is created and registered.
UUID: 15efe6ad-68d1-4df0-8c3f-37fe47e5b38f
Settings file: '/Users/laurent/VirtualBox VMs/boot2docker-vm/boot2docker-vm.vbox'
2015/01/28 14:12:13 executing: VBoxManage showvminfo boot2docker-vm --machinereadable
2015/01/28 14:12:13 executing: VBoxManage setextradata boot2docker-vm VBoxInternal/CPUM/EnableHVP 1
2015/01/28 14:12:13 executing: VBoxManage modifyvm boot2docker-vm --firmware bios --bioslogofadein off --bioslogofadeout off --bioslogodisplaytime 0 --biosbootmenu disabled --natdnshostresolver1 off --natdnsproxy1 off --ostype Linux26_64 --cpus 4 --memory 2048 --vram 8 --acpi on --ioapic on --rtcuseutc on --cpuhotplug off --pae on --longmode on --synthcpu off --hpet on --hwvirtex on --triplefaultreset off --nestedpaging on --largepages on --vtxvpid on --vtxux off --accelerate3d off --uart1 0x3F8 4 --uartmode1 server /Users/laurent/.boot2docker/boot2docker-vm.sock --boot1 dvd
2015/01/28 14:12:13 executing: VBoxManage showvminfo boot2docker-vm --machinereadable
2015/01/28 14:12:13 executing: VBoxManage modifyvm boot2docker-vm --nic1 nat --nictype1 virtio --cableconnected1 on
2015/01/28 14:12:13 executing: VBoxManage controlvm boot2docker-vm natpf1 ssh,tcp,127.0.0.1,2022,,22
2015/01/28 14:12:13 executing: VBoxManage list hostonlyifs
2015/01/28 14:12:13 executing: VBoxManage list dhcpservers
2015/01/28 14:12:13 executing: VBoxManage hostonlyif create
0%...10%...20%...30%...40%...50%...60%...70%...80%...90%...100%
2015/01/28 14:12:13 executing: VBoxManage hostonlyif ipconfig vboxnet6 --ip 192.168.59.3 --netmask 255.255.255.0
2015/01/28 14:12:13 executing: VBoxManage list dhcpservers
2015/01/28 14:12:13 executing: VBoxManage dhcpserver add --netname HostInterfaceNetworking-vboxnet6 --ip 192.168.59.99 --netmask 255.255.255.0 --lowerip 192.168.59.103 --upperip 192.168.59.254 --enable
2015/01/28 14:12:13 executing: VBoxManage modifyvm boot2docker-vm --nic2 hostonly --nictype2 virtio --cableconnected2 on --hostonlyadapter2 vboxnet6
2015/01/28 14:12:14 executing: VBoxManage storagectl boot2docker-vm --name SATA --add sata --portcount 4 --hostiocache on --bootable on
2015/01/28 14:12:14 executing: VBoxManage storageattach boot2docker-vm --storagectl SATA --port 0 --device 0 --type dvddrive --medium /Users/laurent/.boot2docker/boot2docker.iso
Converting from raw image file="stdin" to file="/Users/laurent/VirtualBox VMs/boot2docker-vm/boot2docker-vm.vmdk"...
Creating dynamic image with size 20971520000 bytes (20000MB)...
Initializing disk with ssh keys
...
````

**Closed** 2015-02-24 22:51 UTC

**Comment by tianon** [comment] 2015-02-24 23:01
Now that #324 has merged, can we get someone who can duplicate the issue to test and verify that actually unsetting the offending variables instead of just emptying them out actually does fix it? :smile:

**Comment by gmlewis** [comment] 2015-02-24 23:04
I have not been able to duplicate the issue... sorry.

**Comment by kordless** [comment] 2015-02-25 21:05
I can confirm, using the latest versions of boot2docker (1.5.0) and virtualbox (4.3.22.r98236) that this issue persists. I did everything I found on the Internets as suggestions (reinstall, install with brew, blow away existing VMs, use VB GUI to add/delete interfaces) before stumbling upon this issue here (which ironically was just closed within the day).

Again, the solution was to do the following:

    unset DYLD_LIBRARY_PATH
    unset LD_LIBRARY_PATH

**Comment by nicolashery** [comment] 2015-04-07 14:52
Unsetting the `DYLD_LIBRARY_PATH` and `LD_LIBRARY_PATH` variables didn't immediately work for me. I opened the VirtualBox GUI, and removed all of the VMs there (some where "trash", i.e. I had removed them manually already). Then (with the GUI still open, but not sure if that matters), I ran `boot2docker init` and it worked.

Had installed `boot2docker 1.5.0` via `brew` and `virtualbox 4.3.26-98988` via `brew cask`. Running `OS X 10.8.5`.

Since I didn't really have a "clean slate" before doing this (had tried reinstalling, manually removing VMs etc.) before doing this, I'm not sure what effect the VirtualBox GUI had, but thought I'd post it here in case someone had this issue again.

**Comment by perryn** [comment] 2015-04-24 06:05
I ran into this issue with

boot2docker 1.5.0 
VirtualBox 4.3.4

I did not have and DYLD_ or LD_ set.

I opened the VirtualBox GUI and then 'boot2docker init' worked.

I then closed the VirtualBox GUI and then 'boot2docker init' *still* worked.
